from distutils.core import setup

setup(
    name='pyTGF',
    version='',
    packages=['build.lib.pytgf', 'build.lib.pytgf.ai', 'build.lib.pytgf.ai.deeplearn', 'build.lib.pytgf.data',
              'build.lib.pytgf.game', 'build.lib.pytgf.menu', 'build.lib.pytgf.test', 'build.lib.pytgf.test.test_data',
              'build.lib.pytgf.test.test_board', 'build.lib.pytgf.test.test_controls',
              'build.lib.pytgf.test.test_controls.wrappers', 'build.lib.pytgf.test.test_controls.controllers',
              'build.lib.pytgf.test.test_examples', 'build.lib.pytgf.test.test_characters',
              'build.lib.pytgf.test.test_characters.moves', 'build.lib.pytgf.test.test_characters.units',
              'build.lib.pytgf.board', 'build.lib.pytgf.utils', 'build.lib.pytgf.controls',
              'build.lib.pytgf.controls.events', 'build.lib.pytgf.controls.wrappers',
              'build.lib.pytgf.controls.controllers', 'build.lib.pytgf.examples', 'build.lib.pytgf.examples.sokoban',
              'build.lib.pytgf.examples.sokoban.res.AIs', 'build.lib.pytgf.examples.sokoban.rules',
              'build.lib.pytgf.examples.sokoban.units', 'build.lib.pytgf.examples.sokoban.parsing',
              'build.lib.pytgf.examples.sokoban.controllers', 'build.lib.pytgf.examples.connect4',
              'build.lib.pytgf.examples.connect4.res.AIs', 'build.lib.pytgf.examples.connect4.data',
              'build.lib.pytgf.examples.connect4.rules', 'build.lib.pytgf.examples.connect4.units',
              'build.lib.pytgf.examples.connect4.controllers', 'build.lib.pytgf.examples.lazerbike',
              'build.lib.pytgf.examples.lazerbike.res.AIs', 'build.lib.pytgf.examples.lazerbike.data',
              'build.lib.pytgf.examples.lazerbike.rules', 'build.lib.pytgf.examples.lazerbike.units',
              'build.lib.pytgf.examples.lazerbike.control', 'build.lib.pytgf.characters',
              'build.lib.pytgf.characters.moves', 'build.lib.pytgf.characters.units',
              'build.lib.pytgf.characters.utils', 'pytgf', 'pytgf.ai', 'pytgf.ai.deeplearn', 'pytgf.data', 'pytgf.game',
              'pytgf.menu', 'pytgf.test', 'pytgf.test.test_data', 'pytgf.test.test_board', 'pytgf.test.test_controls',
              'pytgf.test.test_controls.wrappers', 'pytgf.test.test_controls.controllers', 'pytgf.test.test_examples',
              'pytgf.test.test_characters', 'pytgf.test.test_characters.moves', 'pytgf.test.test_characters.units',
              'pytgf.board', 'pytgf.utils', 'pytgf.controls', 'pytgf.controls.events', 'pytgf.controls.wrappers',
              'pytgf.controls.controllers', 'pytgf.examples', 'pytgf.examples.sokoban',
              'pytgf.examples.sokoban.res.AIs', 'pytgf.examples.sokoban.rules', 'pytgf.examples.sokoban.units',
              'pytgf.examples.sokoban.parsing', 'pytgf.examples.sokoban.controllers', 'pytgf.examples.connect4',
              'pytgf.examples.connect4.res.AIs', 'pytgf.examples.connect4.data', 'pytgf.examples.connect4.rules',
              'pytgf.examples.connect4.units', 'pytgf.examples.connect4.controllers', 'pytgf.examples.lazerbike',
              'pytgf.examples.lazerbike.res.AIs', 'pytgf.examples.lazerbike.data', 'pytgf.examples.lazerbike.rules',
              'pytgf.examples.lazerbike.units', 'pytgf.examples.lazerbike.control', 'pytgf.characters',
              'pytgf.characters.moves', 'pytgf.characters.units', 'pytgf.characters.utils'],
    url='https://github.com/Angeall/pyTGF',
    license='MIT',
    author='Anthony Rouneau',
    author_email='angeal1105@gmail.com',
    description='', requires=['multiprocess', 'pathos', 'pygame', 'matplotlib', 'numpy', 'scipy', 'pandas']
)
